### PR TITLE
Bump orangekit packages to `1.0.0-beta.31`

### PR DESCRIPTION
**Pull request by kkosiorowska**
This PR updates the package for `orangeKit/react` to `1.0.0-beta.31`. What's Changed: 

- Ledger accounts support by Xverse
- Reduce the modals displayed to one for Xverse (connection action). Note that only one modal is displayed for Connect wallet modal (+ one additional one for Sign message) so we for the full connecting + signing process we only need 2 modals now instead of 3 for Xverse.

Note that you should use the latest version of the Xverse wallet.

### CODE REVIEW

**Comment by michalinacienciala** [comment]
Issue 1

Steps:
1. Choose `Connect wallet` > Xverse
2. Accept dApp connection
3. Reject SIWE
4. Choose Xverse again

Result:
Two same dApp connection windows displayed:
image

Accepting one of the connections displays SIWE window, the other dapp connection window doesn't disappear. Rejecting that other dapp connection window after signing SIWE from the first window doesn't change anything user is logged in.

Tested on:
https://deploy-preview-729--acre-dapp-testnet.netlify.app/
Xverse version: 0.42.1
Browser: Chrome
Used regular (non-Ledger) address

**Comment by michalinacienciala** [comment]
Issue 2

Steps:
1. Choose `Connect wallet` > Xverse
2. Reject dApp connection

Result:
The dApp connection window displayed again (rejecting it again does not display the window for the third time).

Tested on:
https://deploy-preview-729--acre-dapp-testnet.netlify.app/
Xverse version: 0.42.1
Browser: Chrome
Used regular (non-Ledger) address

**Comment by michalinacienciala** [comment]
### Issue 3

Steps:
1. I successfully logged in using Xverse with `2Mw2Jpu9qs3LueLg7AUuJQ2PQuzThMy781o` account that had ~0.04 BTC. In my Xverse I also had another address added (`2N3jdNg84VULyLwpszq5WP4PASe7oQ6orm3`), with 0 balance
2. I switched the address in Xverse to `2N3jdNg84VULyLwpszq5WP4PASe7oQ6orm3`. Nothing has changed in the Acre UI, I was still shown as connected with `2Mw2Jpu9qs3LueLg7AUuJQ2PQuzThMy781o`.
3. I tried to do a deposit.

Result:
I did not get to sign the transaction, Xverse displayed a `Insufficient balance when including transaction fees` error:
image
So this suggests that wallet or dapp tried to use `2N3jdNg84VULyLwpszq5WP4PASe7oQ6orm3` to sign the transaction.

Interestingly, the same scenario, but with withdrawal behaved differently - I got to see the message signing window in Xverse (showing that signing will be done using my original `2Mw2Jpu9qs3LueLg7AUuJQ2PQuzThMy781o` address) and when I signed the message the withdrawal  was correctly initiated.
image


Tested on:
https://deploy-preview-729--acre-dapp-testnet.netlify.app/
Xverse version: 0.42.1
Browser: Chrome
Used regular (non-Ledger) address

**Comment by michalinacienciala** [comment]
### Issue 4 (?)

I'm not quite sure if this is a bug or not...

Steps:
1. Successfully connect to Acre using Ledger via Xverse
2. Wait for the Ledger device to log out (i.e. wait till it shows the PIN screen) or disconnect it and connect it again, without providing PIN
3. Try to initiate deposit

Result:
After clicking `Confirm` on the message signature window in Xverse and Continuing on the next info window, you get `Transaction failed` error in Xverse and `Unexpected error` in Acre:

image
image

https://github.com/user-attachments/assets/ead304d6-d4bd-4ace-9c7f-e9ebf4fef763

Tested on
https://deploy-preview-729--acre-dapp.netlify.app/ (mainnet, 8ce12383)
Ledger Live: 2.84.1
Bitcoin app: 2.3.0
Xverse: 0.42.1

**Comment by michalinacienciala** [comment]
### Issue 5 (?)

Not sure if this is something we can easily fix and if it is even an issue on our side. I suspect it's issue on Xverse site, but would like to get a confirmation.

The same behavior is observed in Mezo.

Steps:
1. Have a Ledger device imported to Xverse.
2. Connect Ledger device to computer, but do not unlock it.
3. Try connecting to Acre using Ledger via Xverse. Confirm every step (dapp connection, SIWE) until you see `Connect Your Ledger` popup in Xverse with the spinning wheel on one of the buttons:
image

4. Enter PIN. Spinning wheel still shown
5. Enter Bitcoin app. Spinning wheel still shown.

So the issue here is that Xverse seems to not discover that at some point Ledger got unlocked and Bitcoin app got entered, meaning that the blockers for transaction signing are resolved now.

Tested on
https://deploy-preview-729--acre-dapp.netlify.app/ (mainnet, https://github.com/thesis/acre/commit/8ce12383e115defb668a284069ed4e6eba2bc201)
Ledger Live: 2.84.1
Bitcoin app: 2.3.0
Xverse: 0.42.1

**Comment by michalinacienciala** [comment]
## Summary of tests

### Tests done using 'regular' Xverse account

- [x] Reject dapp connection > **NOOK ([ISSUE 2](https://github.com/thesis/acre/pull/729#issuecomment-2363347756))**
- [x] Accept dapp connection, Cancel SIWE > **OK**
- [x] Accept dapp connection, Cancel SIWE, Xverse > **NOOK ([ISSUE 1](https://github.com/thesis/acre/pull/729#issuecomment-2363344825))**
- [x] Accept dapp connection, accept SIWE > **OK**
- [x] Logout > **OK**
- [x] Log in after logging out > **OK**
- [x] Page refresh after logging in, log in again > **OK**
- [x] Change wallet addresses in the extension > **OK**
- [x] Change network in the extension > **OK**
- [x] Try doing deposit after switching in wallet to different address > **NOOK ([ISSUE 3](https://github.com/thesis/acre/pull/729#issuecomment-2363440318))**
- [x] Try doing withdraw after switching in wallet to different address > **OK**
- [x] Try doing deposit/withdraw after switching in wallet to different network > NOOK? `Transaction failed` (asked about this behavior on [Discord](https://discord.com/channels/1079490158639976609/1283790424263233659/1287791093337030709))
- [x] Withdraw, reject > 
- [x] Withdraw, sign > **OK**
- [x] Deposit, reject > **OK**
- [x] Deposit, sign > **OK**

### Tests done using Ledger account via Xverse

- [x] Reject dapp connection > **NOOK ([ISSUE 2](https://github.com/thesis/acre/pull/729#issuecomment-2363347756))**
- [x] Accept dapp connection, Cancel SIWE > **OK**
- [x] Accept dapp connection, Cancel SIWE, Xverse > **NOOK ([ISSUE 1](https://github.com/thesis/acre/pull/729#issuecomment-2363344825))**
- [x] Accept dapp connection, 'Sign' SIWE, 'Cancel' > **OK**
- [x] Accept dapp connection, 'Sign' SIWE, 'Connect', 'Cancel' > **OK**
- [x] Accept dapp connection, 'Sign' SIWE, 'Connect', reject signature in Ledger > OK? 'Invalid request' in Xverse, Close > **OK**
- [x] Accept dapp connection, 'Sign' SIWE, 'Connect' while not logged in to Ledger, enter PIN in Ledger, enter Bitcoin app > NOOK? ([ISSUE 5](https://github.com/thesis/acre/pull/729#issuecomment-2368467134))
- [x] Accept dapp connection, 'Sign' SIWE, 'Connect' while logged in, but not in the Bitcoin app > NOOK? ([ISSUE 5](https://github.com/thesis/acre/pull/729#issuecomment-2368467134))
- [x] Accept dapp connection, accept SIWE > **OK**
- [x] Logout > **OK**
- [x] Log in after logging out > **OK**
- [x] Page refresh after logging in, log in again > **OK**
- [x] Change wallet addresses in the extension > **OK**
- [x] Change network in the extension > **OK**
- [x] Try doing deposit after switching in wallet to different address > **NOOK ([ISSUE 3](https://github.com/thesis/acre/pull/729#issuecomment-2363440318))**
- [x] Try doing withdraw after switching in wallet to different address > **OK**
- [x] Try doing deposit/withdraw after switching in wallet to different network > **NOOK? `Transaction failed` (asked about this behavior on [Discord](https://discord.com/channels/1079490158639976609/1283790424263233659/1287791093337030709))**
- [x] Withdraw, cancel while assembling 1st tx > **OK? (after cancelling we can still see the `Negotiated version...` in logs but after a while we have `Transaction succesfull... ` in logs followed by `Withdrawal cancelled`. The tx id: https://etherscan.io/tx/0xbd9eb493405d2f835b282a5c367eb826f304bee582fb7403e33dfb5bea478b4f#eventlog.)**
- [x] Withdraw, cancel in Xverse sign window > **OK**
- [x] Withdraw, locked Ledger > **OK**
- [x] Withdraw, unlocked Ledger, not in Bitcoin app > NOOK? ([ISSUE 5](https://github.com/thesis/acre/pull/729#issuecomment-2368467134))
- [ ] Withdraw, sign > 
- [x] Deposit, reject > **OK**
- [x] Deposit, sign ('Confirm'), Cancel > **OK**
- [x] Deposit, sign ('Confirm'), Connect, X > **OK**
- [x] Deposit, sign('Confirm'), Connect, Continue (while locked) > **NOOK? ([ISSUE 4](https://github.com/thesis/acre/pull/729#issuecomment-2368322875))**
- [x] Deposit, sign('Confirm'), Connect, Continue (while unlocked, but not in Bitcoin app) > **NOOK? ([ISSUE 4](https://github.com/thesis/acre/pull/729#issuecomment-2368322875))**
- [x] Deposit, sign('Confirm'), Connect, Continue, reject signature in Ledger > **NOOK? ([ISSUE 4](https://github.com/thesis/acre/pull/729#issuecomment-2368322875))**
- [x] Deposit, sign > **OK**

**Comment by kkosiorowska** [comment]
> [Issue 1](https://github.com/thesis/acre/pull/729#issuecomment-2363344825)

> [Issue 2](https://github.com/thesis/acre/pull/729#issuecomment-2363347756)

Fix in https://github.com/thesis/acre/pull/731.

> [Issue 3](https://github.com/thesis/acre/pull/729#issuecomment-2363440318)

Currently, OrangeKit does not notify the dApp about account switching. I created a special task for this problem -https://github.com/thesis/orangekit/issues/132. Hopefully, we'll get to it soon.

> [Issue 4](https://github.com/thesis/acre/pull/729#issuecomment-2368322875)

I believe it is not a bug because we catch that something is wrong and display an error message. But definitely in this case the error messages should be more precise. I see that in the console we get a message about what is wrong so we can improve it. @michalinacienciala please create a separate task for this.

Screenshot 2024-09-24 at 09 44 40

> [Issue 5](https://github.com/thesis/acre/pull/729#issuecomment-2368467134)

Sounds like a problem on the Xverse side. However, I will investigate the issue and let you know.

**Comment by kkosiorowska** [comment]
>  Withdraw, cancel while assembling 1st tx > OK? (after cancelling we can still see the Negotiated version... in logs but after a while we have Transaction succesfull...  in logs followed by Withdrawal cancelled. The tx id: https://etherscan.io/tx/0xbd9eb493405d2f835b282a5c367eb826f304bee582fb7403e33dfb5bea478b4f#eventlog.)

I confirmed it with @r-czajkowski. This transaction is sent on behalf of the bitcoin address corresponding to the safe. It is always sent when the user uses a given BTC address for the first time.

**Comment by michalinacienciala** [comment]
Let's update the OrangeKit to 1.00-beta.32 version (which contains this change: https://github.com/thesis/orangekit/pull/141/files). This can help with the issue with Safe creation that we had luck to catch in Mezo, but not in Acre.
Once we have that change in, I think we can merge the PR - all issues observed during earlier tests have been either resolved or moved outside the scope of the PR. There wasn't anything major observed, Xverse works with Ledger and regular accounts pretty smooth now.

**Review by michalinacienciala — APPROVED** [review]

**Pull request merged**
